spring.application.name=CVProcessor

# test database config (only in-memory, the records are deleted when the program stops)
#spring.datasource.url=jdbc:h2:mem:hogwartdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.h2.console.enabled=true

# database stored in a file
spring.datasource.url=jdbc:h2:file:./data/hogwartdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
google.drive.key-path=Credentials/uni-drive-key.json
google.api.scopes.drive=cloud-api@hogwartcvprocessor.iam.gserviceaccount.com
google.account.mail=hogwarthrdc23@gmail.com
google.account.app-password=sevl zuno ldil qnti


